In [97]:
agents = [
    {
        "Agent": 1,
        "Social Info": {
            "function": "manager",
            "employment_time": 10,
            "friendliness": 8,
            "openness": 8,
            "neuroticism": 7,
            "conscientiousness": 6,
            "agreeableness": 9,
            "extraversion": 9,
            "social_group": "medium",
            "hobby": "marathons"
        },
        "Experiences": {
            "direct": {
                "efficiency": 6,
                "accuracy": 8,
                "flexibility": 2,
                "creativity": 5,
                "helpful": 8
            },
            "communicated": {
                "efficiency": 4,
                "flexibility": 9,
                "accuracy": 1,
                "creativity": 3,
                "helpful": 8
            }
        },
        "Reputation score": 8
    },
    {
        "Agent": 2,
        "Social Info": {
            "function": "loader",
            "employment_time": 10,
            "friendliness": 9,
            "openness": 6,
            "neuroticism": 5,
            "conscientiousness": 9,
            "agreeableness": 9,
            "extraversion": 6,
            "social_group": "medium",
            "hobby": "dance"
        },
        "Experiences": {
            "direct": {
                "efficiency": 5,
                "accuracy": 5,
                "flexibility": 3,
                "creativity": 1,
                "helpful": 4,
            },
            "communicated": {
                "efficiency": 5,
                "flexibility": 5,
                "accuracy": 5,
                "creativity": 5,
                "helpful": 5
            }
        },
        "Reputation score": 7
    },
    {
        "Agent": 3,
        "Social Info": {
            "function": "associate",
            "employment_time": 4,
            "friendliness": 9,
            "openness": 7,
            "neuroticism": 7,
            "conscientiousness": 9,
            "agreeableness": 9,
            "extraversion": 8,
            "social_group": "large",
            "hobby": "novelist"
        },
        "Experiences": {
            "direct": {
                "efficiency": 6,
                "accuracy": 9,
                "flexibility": 9,
                "creativity": 9,
                "helpful": 9
            },
            "communicated": {
                "efficiency": 6,
                "accuracy": 9,
                "flexibility": 8,
                "creativity": 9,
                "helpful": 8
            }
        },
        "Reputation score": 8
    },
    {
        "Agent": 4,
        "Social Info": {
            "function": "forklift driver",
            "employment_time": 15,
            "friendliness": 5,
            "openness": 4,
            "neuroticism": 3,
            "conscientiousness": 8,
            "agreeableness": 3,
            "extraversion": 8,
            "social_group": "medium",
            "hobby": "photographer"
        },
        "Experiences": {
            "direct": {
                "efficiency": 6,
                "accuracy": 9,
                "flexibility": 3,
                "creativity": 1,
                "helpful": 5
            },
            "communicated": {
                "efficiency": 6,
                "accuracy": 6,
                "flexibility": 2,
                "creativity": 4,
                "helpful": 5
            }
        },
        "Reputation score": 7
    },
    {
        "Agent": 5,
        "Social Info": {
            "function": "machine operator",
            "employment_time": 9,
            "friendliness": 8,
            "openness": 4,
            "neuroticism": 5,
            "conscientiousness": 9,
            "agreeableness": 8,
            "extraversion": 7,
            "social_group": "medium",
            "hobby": "gym"
        },
        "Experiences": {
            "direct": {
                "efficiency": 5,
                "accuracy": 6,
                "flexibility": 5,
                "creativity": 5,
                "helpful": 7
            },
            "communicated": {
                "efficiency": 6,
                "accuracy": 6,
                "flexibility": 6,
                "creativity": 9,
                "helpful": 5
            }
        },
        "Reputation score": 9
    },
    {
        "Agent": 6,
        "Social Info": {
            "function": "loader",
            "employment_time": 3,
            "friendliness": 9,
            "openness": 5,
            "neuroticism": 7,
            "conscientiousness": 8,
            "agreeableness": 8,
            "extraversion": 7,
            "social_group": "small",
            "hobby": "fishing"
        },
        "Experiences": {
            "direct": {
                "efficiency": 5,
                "accuracy": 5,
                "flexibility": 6,
                "creativity": 7,
                "helpful": 6
            },
            "communicated": {
                "efficiency": 5,
                "flexibility": 5,
                "accuracy": 5,
                "creativity": 5,
                "helpful": 5
            }
        },
        "Reputation score": 8
    },
    {
        "Agent": 7,
        "Social Info": {
            "function": "associate",
            "employment_time": 10,
            "friendliness": 7,
            "openness": 7,
            "neuroticism": 9,
            "conscientiousness": 6,
            "agreeableness": 9,
            "extraversion": 8,
            "social_group": "large",
            "hobby": "writing"
        },
        "Experiences": {
            "direct": {
                "efficiency": 6,
                "accuracy": 6,
                "flexibility": 7,
                "creativity": 8,
                "helpful": 7
            },
            "communicated": {
                "efficiency": 6,
                "accuracy": 6,
                "flexibility": 6,
                "creativity": 9,
                "helpful": 7
            }
        },
        "Reputation score": 6
    }
]

#for agent in agents:
    


In [98]:
import numpy as np

functionValue = {"manager": 0, "loader": 5, "associate": 2, "forklift driver": 3, "machine operator": 4}
socialGroupValue = {"small": 0, "medium": 1, "large": 2}
#encode function and social group
for agent in agents:
    function = agent["Social Info"]["function"]
    agent["Social Info"]["function"] = functionValue[function]

    socialgroup = agent["Social Info"]["social_group"]
    agent["Social Info"]["social_group"] = socialGroupValue[socialgroup]
print(agents)



[{'Agent': 1, 'Social Info': {'function': 0, 'employment_time': 10, 'friendliness': 8, 'openness': 8, 'neuroticism': 7, 'conscientiousness': 6, 'agreeableness': 9, 'extraversion': 9, 'social_group': 1, 'hobby': 'marathons'}, 'Experiences': {'direct': {'efficiency': 6, 'accuracy': 8, 'flexibility': 2, 'creativity': 5, 'helpful': 8}, 'communicated': {'efficiency': 4, 'flexibility': 9, 'accuracy': 1, 'creativity': 3, 'helpful': 8}}, 'Reputation score': 8}, {'Agent': 2, 'Social Info': {'function': 5, 'employment_time': 10, 'friendliness': 9, 'openness': 6, 'neuroticism': 5, 'conscientiousness': 9, 'agreeableness': 9, 'extraversion': 6, 'social_group': 1, 'hobby': 'dance'}, 'Experiences': {'direct': {'efficiency': 5, 'accuracy': 5, 'flexibility': 3, 'creativity': 1, 'helpful': 4}, 'communicated': {'efficiency': 5, 'flexibility': 5, 'accuracy': 5, 'creativity': 5, 'helpful': 5}}, 'Reputation score': 7}, {'Agent': 3, 'Social Info': {'function': 2, 'employment_time': 4, 'friendliness': 9, 'ope

In [102]:
task1Score = []
task2Score = []

SocialInfoweights1 = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]).reshape(-1, 1)
DirectExpweights1 = np.array([0.1, 0.1, 0.1, 0.1,0.1]).reshape(-1, 1)
CommunicatedExpweights1 = np.array([0.1, 0.1, 0.1, 0.1, 0.1]).reshape(-1, 1)

SocialInfoweights2 = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]).reshape(-1, 1)
DirectExpweights2 = np.array([ 0.1, 0.1, 0.1, 0.1, 0.1]).reshape(-1, 1)
CommunicatedExpweights2 = np.array([0.1, 0.1, 0.1, 0.1, 0.1]).reshape(-1, 1)

#calculate the reputation score
for agent in agents:
    print(np.array(list(agent["Social Info"].values())[:-1]))

    print(SocialInfoweights1)

    tsk1Scorei = np.array(list(agent["Social Info"].values())[:-1]).dot(SocialInfoweights1) + np.array(list(agent["Experiences"]["direct"].values())).dot(DirectExpweights1) + np.array(list(agent["Experiences"]["communicated"].values())).dot(CommunicatedExpweights1)
    tsk2Scorei = np.array(list(agent["Social Info"].values())[:-1]).dot(SocialInfoweights2) + np.array(list(agent["Experiences"]["direct"].values())).dot(DirectExpweights2) + np.array(list(agent["Experiences"]["communicated"].values())).dot(CommunicatedExpweights2)

    task1Score.append(tsk1Scorei)
    task2Score.append(tsk2Scorei)

print("The agent with the highest score for the first task is agent", np.argmax(task1Score))
print("The agent with the highest score for the second task is agent", np.argmax(task2Score))


[ 0 10  8  8  7  6  9  9  1]
[[0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]]
[ 5 10  9  6  5  9  9  6  1]
[[0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]]
[2 4 9 7 7 9 9 8 2]
[[0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]]
[ 3 15  5  4  3  8  3  8  1]
[[0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]]
[4 9 8 4 5 9 8 7 1]
[[0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]]
[5 3 9 5 7 8 8 7 0]
[[0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]]
[ 2 10  7  7  9  6  9  8  2]
[[0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]]
The agent with the highest score for the first task is agent 2
The agent with the highest score for the second task is agent 2
